### ISSUE TITLE
No base64png in svg

### ISSUE THREAD

**Issue by Majorfi** [SmolDapp/tokenAssets#117]
The following icons are base64 PNG in SVG and **must** be updated.
A check will be added in the checks to prevent base64 svg

`1/0x447ddd4960d9fdbf6af9a790560d0af76795cb08` @0xBasically
`10/0x28b42698caf46b4b012cf38b6c75867e0762186d` @ethzoomer
`10/0x74ccbe53f77b08632ce0cb91d3a545bf6b8e0979` @ethzoomer
`10/0x894134a25a5fac1c2c26f1d8fbf05111a3cb9487` @ethzoomer
`10/0xb532178708814f0c174b29b991d2b355106afbc3` @ethzoomer
`10/0xbc7b1ff1c6989f006a1185318ed4e7b5796e66e1` @ethzoomer
`10/0xc1c167cc44f7923cd0062c4370df962f9ddb16f5` @stas
`10/0xc26921b5b9ee80773774d36c84328ccb22c3a819` @stas
`8453/0x6b4712ae9797c199edd44f897ca09bc57628a1cf` @ethzoomer
`8453/0x74ccbe53f77b08632ce0cb91d3a545bf6b8e0979` @ethzoomer
`8453/0x8544fe9d190fd7ec52860abbf45088e81ee24a8c` @ethzoomer
`8453/0xba5e6fa2f33f3955f0cef50c63dcc84861eab663` @ethzoomer
`8453/0xf34e0cff046e154cafcae502c7541b9e5fd8c249` @ethzoomer
`8453/0xff8adec2221f9f4d8dfbafa6b9a297d17603493d` @ethzoomer
`8453/0xffa3f8737c39e36dec4300b162c2153c67c8352f` @0xBasically

**Comment by 0xBasically** [comment]
feel free to delete and we can re-add them
