### ISSUE TITLE
Need help with adding Basenji Logo to Aerodrome 

### ISSUE THREAD

**Issue by BasenjiBase** [SmolDapp/tokenAssets#322]
![photo_2024-05-16 19 14 41](https://github.com/SmolDapp/tokenAssets/assets/165293141/68961214-aebb-4b91-9073-62fd80e964c2) Svg file 

Meet Basenji, the oldest dog breed in history, born to live on the Base Chain.

$BENJI
TG: https://t.me/BasenjiBaseOfficial
Website: https://www.basenjibase.com/
Twitter: https://twitter.com/basenjiofficial

**Comment by abmisx0** [comment]
The SVG is perfect, I'll make the PR.
